# Generated by Django 5.1.6 on 2025-05-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageindex', '0002_alter_job_company_alter_application_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, to='pageindex.skill'),
        ),
    ]
